OpenSnowMap
leaflet-extras/leaflet-providers pull request #379
Opened 2021-02-23 19:58 UTC by stell

BaseLayer is restricted access but the pistes Overlay is great.

2021-02-24 10:42 UTC, brunob requested changes

2021-02-24 10:42 UTC, brunob commented on leaflet-providers.js
> +				attribution: 'Map data: {attribution.OpenStreetMap} | contributors ODBL and www.opensnowmap.org CC-BY-SA'
It would be nice to put a link on www.opensnowmap.org url ?

2021-02-28 19:01 UTC, brunob commented
@jieter any thoughts ?

2021-03-01 12:12 UTC, jieter commented
Looks good, nice cleanup too!

2021-03-01 12:15 UTC, merged

2021-03-01 12:16 UTC, brunob commented
thx @stell for the PR & @jieter for the feedback, i'll put this one in https://github.com/leaflet-extras/leaflet-providers/blob/master/preview/preview.js